- name:  copy_file_and_reload
  hosts: all
  gather_facts:  false
  vars:
      target_path: /opt/file_sd
  tasks:
      - name: copy target file
        copy:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: root1
          group: root1
          force: true
        with_items:
          - { src: '{{ src_sd_file_name }}', dest: '{{ target_path }}/{{ dest_sd_file_name }}' }

      - name: reload_service
        shell: /usr/bin/curl -X POST http://localhost:9090/-/reload &